### PR TITLE
added shell.nix

### LINKED ISSUE #59: missing how to install/use pymadcad on nixos
hi

As nixos user who wants to use this package and contribute to i need an install instruction.

Since nixos is linux distro, but very different from the most common distros the "pip install" instruction installation will be insufficient for a nixos system.

### PR DESCRIPTION
**Pull request by GlennWSo**
Added a shell for the convenience of nixos users.
This file will be helpfull for nixos user who just wants use pymadcad and for those who want to contribute. 

resolves #59

### CODE REVIEW

**Comment by jimy-byerley** [comment]
I understand the need for convenience for contributors
However I have 2 questions about this PR:

- I personally do not use nixos and do not know muc habout it. As nixos is not one of the mainstream distributions at the moment, I do not plan (yet?) on learning how to work with it, meaning I won't be able to make maintenance on the packaging of pymadcad for nixos. Currently, we were expecting - the user to manually go through `pip` to install pymadcad - and the devs to use `setup.py` and whatever tools they want.
  **If we are about to add packaging support for nixos, would you personally be able to maintain this support all along the way ?**

- We should impose the less possible tools to contributors or users, so our packaging must be minimalistic.
  I can see in this `shell.nix` that few packages are marked for installation along pymadcad, but they are not necessary for pymadcad to work:

    + py.tkinter
       not required as we use PyQt5
    + py.flake8
    + py.black
       not required as no formatter is mendatory in pymadcad, (I personnaly discourage the use of formatters)
    + ipython
       off-topic, since the shell is a user choice
    + pytest
       not required as we currently use visual-checking ... this would change someday but yet it is the way it is
    + and others we can discuss as well

  There is a lot of dev-only tools here, so is the purpose of this `shell.nix` to provide an environments for contributors ? (then we might remove few requirements) or to provide an installable package for users ? (then we might remove much more requirements)
  
I don't know much about nixos, so I might have incorrectly read this file. If so please correct me.

**Comment by GlennWSo** [comment]
U are totaly correct in that it has more stuff then strictly necessery. I was lazy and copied pasted it from another project that I'm working on.

I should try to boil it down to the minimum required for using/develop pymadcad.

**Comment by GlennWSo** [comment]
In nixos apps and binary libs are not stored in the usual places.


Just to give some more context. The shell.nix file (at least in the initial commit of this pr) is very close to what I use for 2 things:  


- developing cad tools dental applications,  i must have something like this to use pymacad as livery
- in my fork pymadcad, I must have something like this to enable "pip install -e path/to/repo/pymadcad"

I just want to share how to make pymadcad work on nixos. That said file should be minimized.

**Comment by GlennWSo** [comment]
"If we are about to add packaging support for nixos, would you personally be able to maintain this support all along the way ?"
I would love to 😊

**Comment by jimy-byerley** [comment]
Well then, if you have a minimized version, I would be happy to merge it

**Pull request closed without merging**
